version: '3.9'

services:
    backend:
        image: instrument
        build: ./
        ports:
            - '8000:8000'

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl:ro

        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - backend

volumes:
    hiretal-data: